language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      before_install:
        - sudo apt-get install python-opengl
        - sudo apt-get install xvfb
        - pip install pyvirtualdisplay
        - pip install pytest-xvfb
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install -r requirements.txt
  - pip install pytest

script: pytest -r a -v

# 'xvfb-run -s \"-screen 0 1400x900x24\" python <your_script.py>'
